version: '3.8'

services:
  db:
    image: mariadb:10.4.32
    container_name: cs_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Persist data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cs_phpmyadmin
    restart: always
    environment:
      PMA_HOST: cs_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db  # Corrected to 'db' instead of 'cs_db'

  cipherstorm:
    build: .
    container_name: cipherstorm
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: cs_db
    depends_on:
      - db  # Corrected to 'db' instead of 'cs_db'

volumes:
  db_data:  # Volume to persist database data
